name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Delete Docker Image and Containers
        run: docker rm -rf project
      - name: Pull Docker Image from Docker hub
        run: docker pull gwonu/project:latest
      - name: Execute Docker Container
        run: docker run -d -p 80:3000 --name project gwonu/project:latest